<?php

use App\Http\Controllers\BillingController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\InwardController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CreditNoteController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\SupplierLedgerController;
use App\Http\Controllers\RateSlabController;
use Illuminate\Support\Facades\Route;

// --- Auth ---
Route::get('/login', [LoginController::class, 'show'])->name('login');
Route::post('/login/otp', [LoginController::class, 'sendOtp'])->name('login.otp');
Route::get('/login/otp', fn () => redirect()->route('login'));
Route::get('/login/verify', fn () => redirect()->route('login'));
Route::post('/login/verify', [LoginController::class, 'verify'])->name('login.verify');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/', fn () => redirect()->route('products.index'));

// --- Public (signed) invoice sharing ---
Route::get('/i/{invoice}', [InvoiceController::class, 'publicShow'])->name('invoices.public')->middleware('signed');
Route::get('/i/{invoice}/pdf', [InvoiceController::class, 'publicPdf'])->name('invoices.public.pdf')->middleware('signed');
Route::get('/l/{partner}', [PaymentController::class, 'publicShow'])->name('ledger.public')->middleware('signed');
Route::get('/l/{partner}/data', [PaymentController::class, 'publicData'])->name('ledger.public.data')->middleware('signed');
Route::get('/l/{partner}/pdf', [PaymentController::class, 'publicPdf'])->name('ledger.public.pdf')->middleware('signed');
Route::get('/c/{creditNote}', [CreditNoteController::class, 'publicShow'])->name('creditnotes.public')->middleware('signed');
Route::get('/c/{creditNote}/pdf', [CreditNoteController::class, 'publicPdf'])->name('creditnotes.public.pdf')->middleware('signed');

// --- Owner ---
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/sales-register', [ReportController::class, 'salesRegister'])->name('reports.sales_register');
    Route::get('/reports/sales-summary', [ReportController::class, 'salesSummary'])->name('reports.sales_summary');
    Route::get('/reports/collections', [ReportController::class, 'collections'])->name('reports.collections');
    Route::get('/reports/outstanding', [ReportController::class, 'outstanding'])->name('reports.outstanding');
    Route::get('/reports/stock', [ReportController::class, 'stock'])->name('reports.stock');
    Route::get('/reports/purchases', [ReportController::class, 'purchases'])->name('reports.purchases');
    Route::get('/reports/gst', [ReportController::class, 'gst'])->name('reports.gst');
    Route::get('/reports/collections', [ReportController::class, 'collections'])->name('reports.collections');
    Route::get('/reports/outstanding', [ReportController::class, 'outstanding'])->name('reports.outstanding');
    Route::get('/reports/stock', [ReportController::class, 'stock'])->name('reports.stock');
    Route::get('/reports/purchases', [ReportController::class, 'purchases'])->name('reports.purchases');
    Route::get('/reports/gst', [ReportController::class, 'gst'])->name('reports.gst');
    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/data', [ProductController::class, 'data'])->name('products.data');
    Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    Route::get('/products/import', [ProductController::class, 'importForm'])->name('products.import.form');
    Route::post('/products/import', [ProductController::class, 'import'])->name('products.import');
    Route::get('/products/import/sample', [ProductController::class, 'sampleCsv'])->name('products.import.sample');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::put('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::get('/products/{product}/slabs', [RateSlabController::class, 'edit'])->name('products.slabs');
    Route::put('/products/{product}/slabs', [RateSlabController::class, 'update'])->name('products.slabs.update');

    Route::get('/billing', [BillingController::class, 'selectPartner'])->name('billing.select');
    Route::get('/billing/catalogue', [BillingController::class, 'catalogue'])->name('billing.catalogue');
    Route::get('/billing/cart', [BillingController::class, 'cart'])->name('billing.cart');
    Route::post('/billing/hold', [BillingController::class, 'holdStore'])->name('billing.hold.store');
    Route::get('/billing/hold', [BillingController::class, 'holdIndex'])->name('billing.hold.index');
    Route::get('/billing/hold/{heldBill}', [BillingController::class, 'holdShow'])->name('billing.hold.show');
    Route::delete('/billing/hold/{heldBill}', [BillingController::class, 'holdDestroy'])->name('billing.hold.destroy');
    Route::get('/billing/checkout', [BillingController::class, 'checkout'])->name('billing.checkout');
    Route::post('/invoices', [InvoiceController::class, 'store'])->name('invoices.store');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/data', [InvoiceController::class, 'data'])->name('invoices.data');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/data', [InvoiceController::class, 'data'])->name('invoices.data');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/data', [InvoiceController::class, 'data'])->name('invoices.data');
    Route::get('/invoices/{invoice}', [InvoiceController::class, 'show'])->name('invoices.show');
    Route::get('/invoices/{invoice}/pdf', [InvoiceController::class, 'pdf'])->name('invoices.pdf');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/data', [OrderController::class, 'data'])->name('orders.data');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show');
    Route::post('/orders/{order}/cancel', [OrderController::class, 'cancel'])->name('orders.cancel');
    Route::post('/payments', [PaymentController::class, 'store'])->name('payments.store');
    Route::get('/inward', [InwardController::class, 'index'])->name('inward.index');
    Route::get('/inward/data', [InwardController::class, 'data'])->name('inward.data');
    Route::get('/inward/create', [InwardController::class, 'create'])->name('inward.create');
    Route::post('/inward', [InwardController::class, 'store'])->name('inward.store');
    Route::get('/inward/{inward}', [InwardController::class, 'show'])->name('inward.show');
    Route::get('/suppliers', [SupplierController::class, 'index'])->name('suppliers.index');
    Route::get('/suppliers/data', [SupplierController::class, 'data'])->name('suppliers.data');
    Route::get('/suppliers/create', [SupplierController::class, 'create'])->name('suppliers.create');
    Route::post('/suppliers', [SupplierController::class, 'store'])->name('suppliers.store');
    Route::get('/suppliers/{supplier}/edit', [SupplierController::class, 'edit'])->name('suppliers.edit');
    Route::put('/suppliers/{supplier}', [SupplierController::class, 'update'])->name('suppliers.update');
    Route::get('/suppliers/{supplier}/ledger', [SupplierLedgerController::class, 'show'])->name('supplier.ledger.show');
    Route::get('/suppliers/{supplier}/ledger/data', [SupplierLedgerController::class, 'data'])->name('supplier.ledger.data');
    Route::get('/suppliers/{supplier}/ledger/pdf', [SupplierLedgerController::class, 'pdf'])->name('supplier.ledger.pdf');
    Route::post('/supplier-bills', [SupplierLedgerController::class, 'storeBill'])->name('supplier.bills.store');
    Route::post('/supplier-payments', [SupplierLedgerController::class, 'storePayment'])->name('supplier.payments.store');
    Route::get('/partners/{partner}/credit-note', [CreditNoteController::class, 'create'])->name('creditnotes.create');
    Route::post('/credit-notes', [CreditNoteController::class, 'store'])->name('creditnotes.store');
    Route::get('/credit-notes/{creditNote}', [CreditNoteController::class, 'show'])->name('creditnotes.show');
    Route::get('/credit-notes/{creditNote}/pdf', [CreditNoteController::class, 'pdf'])->name('creditnotes.pdf');
    Route::get('/partners/{partner}/ledger', [PaymentController::class, 'ledger'])->name('ledger.show');
    Route::get('/partners/{partner}/ledger/data', [PaymentController::class, 'data'])->name('ledger.data');
    Route::get('/partners/{partner}/ledger/pdf', [PaymentController::class, 'pdf'])->name('ledger.pdf');
    Route::get('/settings', [SettingController::class, 'edit'])->name('settings.edit');
    Route::put('/settings', [SettingController::class, 'update'])->name('settings.update');
    Route::get('/billing/checkout', [BillingController::class, 'checkout'])->name('billing.checkout');
    Route::post('/invoices', [InvoiceController::class, 'store'])->name('invoices.store');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/data', [InvoiceController::class, 'data'])->name('invoices.data');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/data', [InvoiceController::class, 'data'])->name('invoices.data');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/data', [InvoiceController::class, 'data'])->name('invoices.data');
    Route::get('/invoices/{invoice}', [InvoiceController::class, 'show'])->name('invoices.show');
    Route::get('/invoices/{invoice}/pdf', [InvoiceController::class, 'pdf'])->name('invoices.pdf');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/data', [OrderController::class, 'data'])->name('orders.data');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show');
    Route::post('/orders/{order}/cancel', [OrderController::class, 'cancel'])->name('orders.cancel');
    Route::post('/payments', [PaymentController::class, 'store'])->name('payments.store');
    Route::get('/inward', [InwardController::class, 'index'])->name('inward.index');
    Route::get('/inward/data', [InwardController::class, 'data'])->name('inward.data');
    Route::get('/inward/create', [InwardController::class, 'create'])->name('inward.create');
    Route::post('/inward', [InwardController::class, 'store'])->name('inward.store');
    Route::get('/inward/{inward}', [InwardController::class, 'show'])->name('inward.show');
    Route::get('/suppliers', [SupplierController::class, 'index'])->name('suppliers.index');
    Route::get('/suppliers/data', [SupplierController::class, 'data'])->name('suppliers.data');
    Route::get('/suppliers/create', [SupplierController::class, 'create'])->name('suppliers.create');
    Route::post('/suppliers', [SupplierController::class, 'store'])->name('suppliers.store');
    Route::get('/suppliers/{supplier}/edit', [SupplierController::class, 'edit'])->name('suppliers.edit');
    Route::put('/suppliers/{supplier}', [SupplierController::class, 'update'])->name('suppliers.update');
    Route::get('/suppliers/{supplier}/ledger', [SupplierLedgerController::class, 'show'])->name('supplier.ledger.show');
    Route::get('/suppliers/{supplier}/ledger/data', [SupplierLedgerController::class, 'data'])->name('supplier.ledger.data');
    Route::get('/suppliers/{supplier}/ledger/pdf', [SupplierLedgerController::class, 'pdf'])->name('supplier.ledger.pdf');
    Route::post('/supplier-bills', [SupplierLedgerController::class, 'storeBill'])->name('supplier.bills.store');
    Route::post('/supplier-payments', [SupplierLedgerController::class, 'storePayment'])->name('supplier.payments.store');
    Route::get('/partners/{partner}/credit-note', [CreditNoteController::class, 'create'])->name('creditnotes.create');
    Route::post('/credit-notes', [CreditNoteController::class, 'store'])->name('creditnotes.store');
    Route::get('/credit-notes/{creditNote}', [CreditNoteController::class, 'show'])->name('creditnotes.show');
    Route::get('/credit-notes/{creditNote}/pdf', [CreditNoteController::class, 'pdf'])->name('creditnotes.pdf');
    Route::get('/partners/{partner}/ledger', [PaymentController::class, 'ledger'])->name('ledger.show');
    Route::get('/partners/{partner}/ledger/data', [PaymentController::class, 'data'])->name('ledger.data');
    Route::get('/partners/{partner}/ledger/pdf', [PaymentController::class, 'pdf'])->name('ledger.pdf');
    Route::get('/settings', [SettingController::class, 'edit'])->name('settings.edit');
    Route::put('/settings', [SettingController::class, 'update'])->name('settings.update');

    Route::get('/partners', [PartnerController::class, 'index'])->name('partners.index');
    Route::get('/partners/data', [PartnerController::class, 'data'])->name('partners.data');
    Route::get('/partners/create', [PartnerController::class, 'create'])->name('partners.create');
    Route::post('/partners', [PartnerController::class, 'store'])->name('partners.store');
    Route::get('/partners/{partner}/edit', [PartnerController::class, 'edit'])->name('partners.edit');
    Route::put('/partners/{partner}', [PartnerController::class, 'update'])->name('partners.update');
});

// --- Retailer (token-based portal; manages its own auth via the API) ---
Route::get('/retailer', fn () => view('retailer.portal'))->name('retailer.home');